package com.github.fkitsantas.pdfcompressionservice.web;

import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Exposes the running build's identity at {@code GET /version} - semantic
 * version, build timestamp, git commit and CI build number - so a deployed
 * instance can be traced back to the exact successful build that produced it.
 *
 * <p>The values come from {@code META-INF/build-info.properties}, generated by
 * the Spring Boot Maven plugin's {@code build-info} goal (see pom.xml) and
 * overridden per build in CI with the run number and commit SHA. {@link
 * BuildProperties} is resolved via {@link ObjectProvider} so the endpoint still
 * responds (with {@code version=unknown}) in the rare case the build-info file
 * is absent, rather than failing to start.
 */
@RestController
public class VersionController {

    private final BuildProperties buildProperties;

    public VersionController(ObjectProvider<BuildProperties> buildProperties) {
        this.buildProperties = buildProperties.getIfAvailable();
    }

    @GetMapping("/version")
    public Map<String, String> version() {
        Map<String, String> info = new LinkedHashMap<>();
        if (buildProperties == null) {
            info.put("version", "unknown");
            return info;
        }
        info.put("name", buildProperties.getName());
        info.put("version", buildProperties.getVersion());
        info.put("buildTime", buildProperties.getTime() != null ? buildProperties.getTime().toString() : null);
        info.put("buildNumber", buildProperties.get("number"));
        info.put("gitSha", buildProperties.get("gitSha"));
        return info;
    }
}
